trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: npm ci
    displayName: 'Install dependencies'

  # Run CRA tests; pass JUnit reporter; jsdom is automatic in CRA
  - script: |
      CI=true npm test -- --watchAll=false --ci \
        --reporters=default --reporters=jest-junit
    displayName: 'Run tests (CRA + JUnit)'
    env:
      # jest-junit output location
      JEST_JUNIT_OUTPUT_DIR: test-results/jest
      JEST_JUNIT_OUTPUT_NAME: junit.xml

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    displayName: 'Publish JUnit results'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'test-results/jest/junit.xml'
      mergeTestResults: true
