# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - script: npm install
    displayName: "npm install"

  - script: npm install --save-dev jest-junit
    displayName: "Install Jest JUnit Reporter"

  - script: npm install --save-dev @babel/core @babel/preset-react @babel/preset-env
    displayName: "Install Babel"

  - script: |
      echo '{"presets": ["@babel/preset-react", "@babel/preset-env"]}' > .babelrc
    displayName: "Configure Babel"

  - script: npx jest --ci --reporters=default --reporters=jest-junit
    displayName: "Run Tests with JUnit Reporter"

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    displayName: "Publish Test Results"
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "**/junit.xml"
      mergeTestResults: true
