trigger:
  branches:
    include:
      - '*'   # build on all branches (incl. main)

pr:
  branches:
    include:
      - '*'   # validate PRs from any branch

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: npm i
    displayName: 'Install dependencies'

  # Run CRA tests; jsdom is built-in. Always publish results, even on failure.
  - script: |
      CI=true npm test -- --watchAll=false --i \
        --reporters=default --reporters=jest-junit
    displayName: 'Run tests (CRA + JUnit)'
    env:
      JEST_JUNIT_OUTPUT_DIR: test-results/jest
      JEST_JUNIT_OUTPUT_NAME: junit.xml

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    displayName: 'Publish JUnit results'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'test-results/jest/junit.xml'
      mergeTestResults: true

  # Only build if tests passed
  - script: npm run build
    displayName: 'Build app'
    condition: succeeded()

  # Publish CRA build output as artifact for Release pipelines
  - task: PublishBuildArtifacts@1
    displayName: 'Publish build artifact'
    condition: succeeded()
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/build'
      ArtifactName: 'drop-$(Build.SourceBranchName)'
      publishLocation: 'Container'
